# We don't need sudo as such, but setting sudo: required allows us to run on
# the faster machines which means that the builds complete much faster (in
# about half the time). For comparison, here are two builds on the two
# different machines:
# - With `sudo: false`: https://travis-ci.org/opbeat/opbeat-node/builds/252301998
# - With `sudo: required`: https://travis-ci.org/opbeat/opbeat-node/builds/252302576
sudo: required

language: node_js

services:
- mysql
- mongodb
- redis-server
- postgresql

node_js:
  - '9'
  - '8'
  - '10'
  - '7.9.0' # currently 7.10.0 fails. For details see: https://github.com/nodejs/node/pull/12861
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'

jobs:
  fast_finish: true

  include:

    # Node.js 9
    - stage: dependencies
      node_js: '9'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '9'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '9'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '9'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 8
    -
      node_js: '8'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '8'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '8'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '8'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 7
    -
      node_js: '7'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '7'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '7'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '7'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 6
    -
      node_js: '6'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '6'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '6'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '6'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 5
    -
      node_js: '5'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '5'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '5'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '5'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 4
    -
      node_js: '4'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '4'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '4'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '4'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 0.12
    -
      node_js: '0.12'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.12'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.12'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.12'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

    # Node.js 0.10
    -
      node_js: '0.10'
      env: TAV=generic-pool,mysql,redis,koa-router
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.10'
      env: TAV=ioredis,pg
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.10'
      env: TAV=bluebird
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'
    -
      node_js: '0.10'
      env: TAV=knex,ws,graphql,express-graphql,hapi
      script: 'if ! [[ $TRAVIS_BRANCH == greenkeeper/* ]]; then tav --quiet; fi'

notifications:
  email:
    - watson@elastic.co
  slack:
    secure: Jq9ST6TYsZZtPgUdn60rZCfcclNF1cXaCqemt9ZKvqlDie9kbyJjU9t0K+EFdlQXgzM5sGAC+okRO9c29zMDuWvsuY6wb5K2p9j1cxfOn1FTc4xcxh/fKelu1Q7nGaMOIPvQuoI/TQBo4pwACyjli+ohz7DMVMRcans6GR+P0S8=
    on_success: change
    on_failure: change
    on_pull_requests: false
